# Generated by Django 5.2.6 on 2025-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('mpesa', 'M-Pesa')], max_length=20)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
