# Generated by Django 5.2.6 on 2025-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidade', models.PositiveIntegerField()),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('atendimento', 'Em Atendimento')], default='livre', max_length=20)),
                ('reserva_data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
